# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWXLViHAFXA2QemJ2kl05sMVbCV04sDS
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import Perceptron    # Used for simple linear classification tasks.

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential     # Sequential lets you build a neural network layer-by-layer in Keras.

from tensorflow.keras.layers import Dense     #Dense makes the final predictions
from tensorflow.keras.layers import Conv2D     # Conv2D extracts features
from tensorflow.keras.layers import Flatten    # Flatten reshapes them

from tensorflow.keras.layers import MaxPooling2D     # MaxPooling2D reduces size
from tensorflow.keras.layers import Dropout          # Dropout prevents overfitting

from tensorflow.keras.utils import to_categorical     # converts numeric class labels into one-hot encoded format for training classification models

df = pd.read_csv("/content/sample_data/mnist_train_small.csv", header=None)
df_test = pd.read_csv("/content/sample_data/mnist_test.csv", header=None)

df.head()

df.columns

df.info()

df.shape

df.isnull().sum()

#preprocess the data
# Column 0 contains the labels, columns 1-784 contain the pixel features.
X_train = df.drop(0, axis=1).values # Drop column 0 (labels) to get features
y_train = df[0].values             # Select column 0 to get labels
X_test = df_test.drop(0, axis=1).values # Do the same for the test set
y_test = df_test[0].values

# Change the every data value beetween 0 to 1
X_train = X_train.astype("float32") / 255.0;
X_test = X_test.astype("float32") / 255.0;

X_train_img = X_train.reshape(-1,28,28);
X_test_img = X_test.reshape(-1,28,28);

# One hot enconding
y_train_cat = to_categorical(y_train,10);
y_test_cat = to_categorical(y_test,10);

perceptron = Sequential([
    Flatten(input_shape=(28,28)),
    Dense(10,activation="softmax")
])

perceptron.compile(optimizer="sgd", loss="categorical_crossentropy", metrics=["accuracy"])

history_percp = perceptron.fit(X_train_img, y_train_cat, epochs=5, batch_size=32, validation_data=
 (X_test_img, y_test_cat), verbose=1)

acc_percp = perceptron.evaluate(X_test_img, y_test_cat, verbose=0)[1]

acc_percp

X_train_cnn = X_train.reshape(-1,28,28,1)
X_test_cnn = X_test.reshape(-1,28,28,1)

cnn = Sequential([
    Conv2D(32, kernel_size=(3,3), activation="relu", input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64, kernel_size=(3,3), activation="relu"),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),
    Dense(10, activation="softmax")
])

cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

history_cnn = cnn.fit(X_train_cnn, y_train_cat, epochs=5, batch_size=32, validation_data=(X_test_cnn, y_test_cat), verbose=1)

acc_cnn = cnn.evaluate(X_test_cnn, y_test_cat, verbose=0)[1]

acc_cnn

"""### Perceptron Model Training History"""

plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1)
plt.plot(history_percp.history['accuracy'])
plt.plot(history_percp.history['val_accuracy'])
plt.title('Perceptron Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history_percp.history['loss'])
plt.plot(history_percp.history['val_loss'])
plt.title('Perceptron Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()

"""### CNN Model Training History"""

plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1)
plt.plot(history_cnn.history['accuracy'])
plt.plot(history_cnn.history['val_accuracy'])
plt.title('CNN Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2)
plt.plot(history_cnn.history['loss'])
plt.plot(history_cnn.history['val_loss'])
plt.title('CNN Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()
